# Generated by Django 2.2.28 on 2025-02-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_pageadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAdmin',
        ),
    ]
