# Generated by Django 2.2.28 on 2025-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_page_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
