# Generated by Django 2.2.28 on 2025-02-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250205_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
